server:
  port: 18080

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/transaction_db
    username: root
    password: password
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: test
        secret-key: test
      sns:
        endpoint: http://localhost:4566
      sqs:
        endpoint: http://localhost:4566