server:
  port: 18080

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/transaction_db
    username: root
    password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true