server:
  port: 18080

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/transaction_db
    username: root
    password: password
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: false
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: test
        secret-key: test
      sns:
        endpoint: http://localhost:14566
        topics:
          reservation-created: arn:aws:sns:ap-northeast-2:000000000000:reservation-created-topic
      sqs:
        endpoint: http://localhost:14566